### ISSUE TITLE
why did I kick me???

### ISSUE THREAD

**Issue by ncdn** [SlumberDemon/EasyCdn#2]

**Comment by SlumberDemon** [comment]
Could you please elaborate, I am having difficulties understanding your issue?

**Comment by ncdn** [comment]
> Could you please elaborate, I am having difficulties understanding your issue?

why did you kick me out of the group, on discord.com

I don't seem to have done anything,   can't I accommodate people?

**Comment by SlumberDemon** [comment]
You have been banned for being a "troll".

**Comment by ncdn** [comment]
what ??

**Comment by SlumberDemon** [comment]
Everyone needs help sometimes but laughing at them is not a solution, its rather insensitive and immature

**Comment by ncdn** [comment]
> Everyone needs help sometimes but laughing at them is not funny.

is it defined by your standard?

**Comment by SlumberDemon** [comment]
I don't make the rules and I did not ban you

**Comment by SlumberDemon** [comment]
I am not 100% what the issue was but that might have been a reason

**Comment by ncdn** [comment]
so, who did it? I need to listen to the explanation

**Comment by SlumberDemon** [comment]
Unfortunately I cannot disclose such information and I would like for you not to create Issues on unrelated matter in my repos

**Comment by ncdn** [comment]
It's completely unreasonable, okay？

**Comment by SlumberDemon** [comment]
I will be closing this issue as its not related to this project

**Comment by ncdn** [comment]
I'm so angry,  baffling

**Comment by SlumberDemon** [comment]
Stop. Please

**Comment by abdelhai** [comment]
it was me who blocked you, @ncdn.
please leave @SlumberDemon alone. i already received your email.

**Comment by SlumberDemon** [comment]
Thanks
