### ISSUE TITLE
u can delete me and block me, but you can't prevent me from requesting a reply

### ISSUE THREAD

**Issue by ncdn** [SlumberDemon/EasyCdn#3]

**Comment by SlumberDemon** [comment]
Please, stop.

**Comment by ncdn** [comment]
for no reason, kicking others out is still in such a big official discussion group. who gives u the power

**Comment by SlumberDemon** [comment]
As said before, I was not the one that removed you

**Comment by ncdn** [comment]
so who is ?!

**Comment by SlumberDemon** [comment]
Also as said before I cannot disclose such information

**Comment by SlumberDemon** [comment]
Stop harassing people unrelated to this issue
